# Generated by Django 5.1.3 on 2024-11-17 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerreviews',
            name='stars',
            field=models.PositiveIntegerField(default=1, verbose_name='stars'),
        ),
    ]
