# Generated by Django 5.1.3 on 2024-11-17 07:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inance', '0002_alter_customerreviews_stars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerreviews',
            name='stars',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(5)], verbose_name='stars'),
        ),
    ]
